### ISSUE TITLE
Outdated GooglePlayServices

### ISSUE THREAD

**Issue by gackerfred** [felixmartens/Wattfinder#1]
Start / loading Screen gets stuck if Google play services version is not high enough. This should lead to some notification pointing to the PlayStore to update them and maybe some error message in the app.

**Comment by gackerfred** [comment]
solution is one line in KartenActivity:

else if (!FilterWorks.filter_initialized())
        {
            **GoogleApiAvailability.getInstance().makeGooglePlayServicesAvailable(this);**
            AnimationWorker.showStartup();
        }

![screenshot_1528209683](https://user-images.githubusercontent.com/18515416/40983358-bbc5786a-68df-11e8-968b-5e87d2c890f0.png)

**Comment by felixmartens** [comment]
added the one-liner as suggested
