### ISSUE TITLE
not all markers shown when more than 500 requested

### ISSUE THREAD

**Issue by gackerfred** [felixmartens/Wattfinder#2]
problem is the duplicate check of a goingelectric request via a hash over the filterParams.
this hash does not include the startkey value, that leads to the followup requests beeing dropped as duplicates, even if the startkey value is different.

simple solution is to add the startkey to the hash, when it is calculated:
`final int hash = FilterWorks.paramsHash()+startkey;`

This makes the markers beeing shown, even if that takes some time.

**Comment by felixmartens** [comment]
should be fixed by last commit
