### ISSUE TITLE
Rendering slowed down by wattfinder.de request

### ISSUE THREAD

**Issue by gackerfred** [felixmartens/Wattfinder#4]
the additional reuquests to wattfinder.de to get the additional data should not be done before all data from goingelectric is there.
removing the wattfinder.de requests, the loading performance gets much better since the goingelectric requets can be done one after the other. 
i suppose to do the additional requests to wattfinder.de not before loading finished, or in paralell if possible.

**Comment by felixmartens** [comment]
they should be in parallel as all Request should be done async via volley. But i will change it so the request will be done after GE-Requests finished
